### ISSUE TITLE
naming of API endpoint strings

### ISSUE THREAD

**Issue by adryd325** [xhyrom-forks/discord-datamining-lang-differ#2]
lang refers to language entries, 

perhaps rename getLangEndpoints.js to getEndpoingsStrings.js

also i'd be willing to merge this upstream once its done

**Comment by xhyrom** [comment]
> lang refers to language entries,
> 
> perhaps rename getLangEndpoints.js to getEndpoingsStrings.js
> 
> also i'd be willing to merge this upstream once its done

sure, I'll do it also I'll be happy if this can be merged into upstream

**Comment by xhyrom** [comment]
@adryd325 i renamed it to "routes", look into commit message why  - https://github.com/xhyrom-forks/discord-datamining-lang-differ/commit/22bca29ec9db82b74d8c68b58a2e75a1d46449e2

what's your opinion?

**Comment by adryd325** [comment]
that looks perfect
